# Generated by Django 4.2.5 on 2023-12-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userClick',
            fields=[
                ('clickid', models.AutoField(db_column='clickID', primary_key=True, serialize=False)),
                ('uid', models.IntegerField(db_column='uID')),
                ('rid', models.IntegerField(db_column='rID')),
                ('ctime', models.DateTimeField(db_column='cTime')),
            ],
            options={
                'db_table': '1_user_click',
                'managed': False,
            },
        ),
    ]
