# Generated by Django 4.2.5 on 2023-12-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollectrest',
            fields=[
                ('collectid', models.AutoField(db_column='collectID', primary_key=True, serialize=False)),
                ('uid', models.IntegerField(db_column='uID')),
                ('rid', models.IntegerField(db_column='rID')),
            ],
            options={
                'db_table': '1_user_collectrest',
                'managed': False,
            },
        ),
    ]
