# Generated by Django 4.2.5 on 2023-09-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(db_column='uID', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('gender', models.IntegerField()),
                ('birthday', models.DateField()),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('verify_password', models.CharField(max_length=20)),
                ('money', models.IntegerField()),
                ('sign', models.DateField(blank=True)),
                ('skin', models.IntegerField()),
            ],
            options={
                'db_table': '1_user_info',
                'managed': False,
            },
        ),
    ]
