# Generated by Django 4.2.2 on 2023-08-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostDetail',
            fields=[
                ('cid', models.AutoField(db_column='cID', primary_key=True, serialize=False)),
                ('uid', models.IntegerField(db_column='uID')),
                ('ResName', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('which_meal', models.IntegerField()),
                ('rid', models.IntegerField(db_column='rID')),
                ('price', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rating', models.IntegerField()),
                ('my_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cost_detail',
            },
        ),
    ]
