# Generated by Django 4.2.2 on 2023-08-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costdetail',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costdetail',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
