# Generated by Django 4.2.4 on 2023-09-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0002_alter_costdetail_price_alter_costdetail_rating'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='costdetail',
            table='1_cost_detail',
        ),
    ]
