# Generated by Django 4.2.4 on 2023-09-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0003_alter_costdetail_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costdetail',
            options={'managed': False},
        ),
    ]
