# Generated by Django 4.2.3 on 2023-07-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('gender', models.IntegerField()),
                ('birthday', models.DateField()),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
