import React, { useEffect, useState } from 'react';
import { StyleSheet, Text, Image, View, SafeAreaView, TouchableOpacity } from 'react-native';
import { globalStyles } from '../../styles/global';
import { useNavigation } from "@react-navigation/native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import Ionicons from 'react-native-vector-icons/Ionicons';
import { link } from '../../data/apiLink';

export default function Myacc() {
  const navigation = useNavigation();
  const [userData, setUserData] = useState({ name: '用戶1號', email: 'userone@gmail.com' });
  const [avatarSource, setAvatarSource] = useState(require("../../assets/images/baby/baby0/90.png"));

  useEffect(() => {
    console.log(userData, avatarSource); // Log the current state values when they change

    const unsubscribe = navigation.addListener('focus', fetchUserData);

    async function fetchUserData() {
      try {
          const userToken = await AsyncStorage.getItem('userToken');
          
          if (userToken) { 
              const response = await fetch(link.myaccGetUsr, {
                  method: 'POST',
                  headers: {
                      'Content-Type': 'application/json',
                      Authorization: `Token ${userToken}`,
                  },
              });
              const responseData = await response.json();

              if(responseData.id && responseData.username && responseData.email && responseData.avatarId) {
                  setUserData({
                      name: responseData.username,
                      email: responseData.email
                  });

                  const images = {
                    1:require("../../assets/images/baby/all/1.png"),
                    2:require("../../assets/images/baby/all/2.png"),
                    3:require("../../assets/images/baby/all/3.png"),
                    4:require("../../assets/images/baby/all/4.png"),
                    5:require("../../assets/images/baby/all/5.png"),
                    6:require("../../assets/images/baby/all/6.png"),
//                    7:require("../../assets/images/baby/all/7.png"),
//                    8:require("../../assets/images/baby/all/8.png"),
//                    9:require("../../assets/images/baby/all/9.png"),
//                    10:require("../../assets/images/baby/all/10.png"),
//                    11:require("../../assets/images/baby/all/11.png"),
//                    12:require("../../assets/images/baby/all/12.png"),
//                    13:require("../../assets/images/baby/all/13.png"),
//                    14:require("../../assets/images/baby/all/14.png"),
//                    15:require("../../assets/images/baby/all/15.png"),
//                    16:require("../../assets/images/baby/all/16.png"),
//                    17:require("../../assets/images/baby/all/17.png"),
//                    18:require("../../assets/images/baby/all/18.png"),
//                    19:require("../../assets/images/baby/all/19.png"),
//                    20:require("../../assets/images/baby/all/20.png"),
//                    21:require("../../assets/images/baby/all/21.png"),
//                    22:require("../../assets/images/baby/all/22.png"),
//                    23:require("../../assets/images/baby/all/23.png"),
//                    24:require("../../assets/images/baby/all/24.png"),
//                    25:require("../../assets/images/baby/all/25.png"),
//                    26:require("../../assets/images/baby/all/26.png"),
//                    27:require("../../assets/images/baby/all/27.png"),
//                    28:require("../../assets/images/baby/all/28.png"),
//                    29:require("../../assets/images/baby/all/29.png"),
//                    30:require("../../assets/images/baby/all/30.png"),
//                    31:require("../../assets/images/baby/all/31.png"),
//                    32:require("../../assets/images/baby/all/32.png"),
//                    33:require("../../assets/images/baby/all/33.png"),
//                    34:require("../../assets/images/baby/all/34.png"),
//                    35:require("../../assets/images/baby/all/35.png"),
//                    36:require("../../assets/images/baby/all/36.png"),
//                    37:require("../../assets/images/baby/all/37.png"),
//                    38:require("../../assets/images/baby/all/38.png"),
//                    39:require("../../assets/images/baby/all/39.png"),
//                    40:require("../../assets/images/baby/all/40.png"),
//                    41:require("../../assets/images/baby/all/41.png"),
//                    42:require("../../assets/images/baby/all/42.png"),
                    43:require("../../assets/images/baby/all/43.png"),
                    44:require("../../assets/images/baby/all/44.png"),
                    45:require("../../assets/images/baby/all/45.png"),
                    46:require("../../assets/images/baby/all/46.png"),
                    47:require("../../assets/images/baby/all/47.png"),
                    48:require("../../assets/images/baby/all/48.png"),
//                    49:require("../../assets/images/baby/all/49.png"),
//                    50:require("../../assets/images/baby/all/50.png"),
//                    51:require("../../assets/images/baby/all/51.png"),
//                    52:require("../../assets/images/baby/all/52.png"),
//                    53:require("../../assets/images/baby/all/53.png"),
//                    54:require("../../assets/images/baby/all/54.png"),
//                    55:require("../../assets/images/baby/all/55.png"),
//                    56:require("../../assets/images/baby/all/56.png"),
//                    57:require("../../assets/images/baby/all/57.png"),
//                    58:require("../../assets/images/baby/all/58.png"),
//                    59:require("../../assets/images/baby/all/59.png"),
//                    60:require("../../assets/images/baby/all/60.png"),
//                    61:require("../../assets/images/baby/all/61.png"),
//                    62:require("../../assets/images/baby/all/62.png"),
//                    63:require("../../assets/images/baby/all/63.png"),
//                    64:require("../../assets/images/baby/all/64.png"),
//                    65:require("../../assets/images/baby/all/65.png"),
//                    66:require("../../assets/images/baby/all/66.png"),
//                    67:require("../../assets/images/baby/all/67.png"),
//                    68:require("../../assets/images/baby/all/68.png"),
//                    69:require("../../assets/images/baby/all/69.png"),
//                    70:require("../../assets/images/baby/all/70.png"),
//                    71:require("../../assets/images/baby/all/71.png"),
//                    72:require("../../assets/images/baby/all/72.png"),
//                    73:require("../../assets/images/baby/all/73.png"),
//                    74:require("../../assets/images/baby/all/74.png"),
//                    75:require("../../assets/images/baby/all/75.png"),
//                    76:require("../../assets/images/baby/all/76.png"),
//                    77:require("../../assets/images/baby/all/77.png"),
//                    78:require("../../assets/images/baby/all/78.png"),
//                    79:require("../../assets/images/baby/all/79.png"),
//                    80:require("../../assets/images/baby/all/80.png"),
//                    81:require("../../assets/images/baby/all/81.png"),
//                    82:require("../../assets/images/baby/all/82.png"),
//                    83:require("../../assets/images/baby/all/83.png"),
//                    84:require("../../assets/images/baby/all/84.png"),
                    85:require("../../assets/images/baby/all/85.png"),
                    86:require("../../assets/images/baby/all/86.png"),
                    87:require("../../assets/images/baby/all/87.png"),
                    88:require("../../assets/images/baby/all/88.png"),
                    89:require("../../assets/images/baby/all/89.png"),
                    90:require("../../assets/images/baby/all/90.png"),
//                    91:require("../../assets/images/baby/all/91.png"),
//                    92:require("../../assets/images/baby/all/92.png"),
//                    93:require("../../assets/images/baby/all/93.png"),
//                    94:require("../../assets/images/baby/all/94.png"),
//                    95:require("../../assets/images/baby/all/95.png"),
//                    96:require("../../assets/images/baby/all/96.png"),
//                    97:require("../../assets/images/baby/all/97.png"),
//                    98:require("../../assets/images/baby/all/98.png"),
//                    99:require("../../assets/images/baby/all/99.png"),
//                    100:require("../../assets/images/baby/all/100.png"),
//                    101:require("../../assets/images/baby/all/101.png"),
//                    102:require("../../assets/images/baby/all/102.png"),
//                    103:require("../../assets/images/baby/all/103.png"),
//                    104:require("../../assets/images/baby/all/104.png"),
//                    105:require("../../assets/images/baby/all/105.png"),
//                    106:require("../../assets/images/baby/all/106.png"),
//                    107:require("../../assets/images/baby/all/107.png"),
//                    108:require("../../assets/images/baby/all/108.png"),
//                    109:require("../../assets/images/baby/all/109.png"),
//                    110:require("../../assets/images/baby/all/110.png"),
//                    111:require("../../assets/images/baby/all/111.png"),
//                    112:require("../../assets/images/baby/all/112.png"),
//                    113:require("../../assets/images/baby/all/113.png"),
//                    114:require("../../assets/images/baby/all/114.png"),
//                    115:require("../../assets/images/baby/all/115.png"),
//                    116:require("../../assets/images/baby/all/116.png"),
//                    117:require("../../assets/images/baby/all/117.png"),
//                    118:require("../../assets/images/baby/all/118.png"),
//                    119:require("../../assets/images/baby/all/119.png"),
//                    120:require("../../assets/images/baby/all/120.png"),
//                    121:require("../../assets/images/baby/all/121.png"),
//                    122:require("../../assets/images/baby/all/122.png"),
//                    123:require("../../assets/images/baby/all/123.png"),
//                    124:require("../../assets/images/baby/all/124.png"),
//                    125:require("../../assets/images/baby/all/125.png"),
//                    126:require("../../assets/images/baby/all/126.png"),
                    127:require("../../assets/images/baby/all/127.png"),
                    128:require("../../assets/images/baby/all/128.png"),
                    129:require("../../assets/images/baby/all/129.png"),
                    130:require("../../assets/images/baby/all/130.png"),
                    131:require("../../assets/images/baby/all/131.png"),
                    132:require("../../assets/images/baby/all/132.png"),
//                    133:require("../../assets/images/baby/all/133.png"),
//                    134:require("../../assets/images/baby/all/134.png"),
//                    135:require("../../assets/images/baby/all/135.png"),
//                    136:require("../../assets/images/baby/all/136.png"),
//                    137:require("../../assets/images/baby/all/137.png"),
//                    138:require("../../assets/images/baby/all/138.png"),
//                    139:require("../../assets/images/baby/all/139.png"),
//                    140:require("../../assets/images/baby/all/140.png"),
//                    141:require("../../assets/images/baby/all/141.png"),
//                    142:require("../../assets/images/baby/all/142.png"),
//                    143:require("../../assets/images/baby/all/143.png"),
//                    144:require("../../assets/images/baby/all/144.png"),
//                    145:require("../../assets/images/baby/all/145.png"),
//                    146:require("../../assets/images/baby/all/146.png"),
//                    147:require("../../assets/images/baby/all/147.png"),
//                    148:require("../../assets/images/baby/all/148.png"),
//                    149:require("../../assets/images/baby/all/149.png"),
//                    150:require("../../assets/images/baby/all/150.png"),
//                    151:require("../../assets/images/baby/all/151.png"),
//                    152:require("../../assets/images/baby/all/152.png"),
//                    153:require("../../assets/images/baby/all/153.png"),
//                    154:require("../../assets/images/baby/all/154.png"),
//                    155:require("../../assets/images/baby/all/155.png"),
//                    156:require("../../assets/images/baby/all/156.png"),
//                    157:require("../../assets/images/baby/all/157.png"),
//                    158:require("../../assets/images/baby/all/158.png"),
//                    159:require("../../assets/images/baby/all/159.png"),
//                    160:require("../../assets/images/baby/all/160.png"),
//                    161:require("../../assets/images/baby/all/161.png"),
//                    162:require("../../assets/images/baby/all/162.png"),
//                    163:require("../../assets/images/baby/all/163.png"),
//                    164:require("../../assets/images/baby/all/164.png"),
//                    165:require("../../assets/images/baby/all/165.png"),
//                    166:require("../../assets/images/baby/all/166.png"),
//                    167:require("../../assets/images/baby/all/167.png"),
//                    168:require("../../assets/images/baby/all/168.png"),
                    169:require("../../assets/images/baby/all/169.png"),
                    170:require("../../assets/images/baby/all/170.png"),
                    171:require("../../assets/images/baby/all/171.png"),
                    172:require("../../assets/images/baby/all/172.png"),
                    173:require("../../assets/images/baby/all/173.png"),
                    174:require("../../assets/images/baby/all/174.png"),
//                    175:require("../../assets/images/baby/all/175.png"),
//                    176:require("../../assets/images/baby/all/176.png"),
//                    177:require("../../assets/images/baby/all/177.png"),
//                    178:require("../../assets/images/baby/all/178.png"),
//                    179:require("../../assets/images/baby/all/179.png"),
//                    180:require("../../assets/images/baby/all/180.png"),
//                    181:require("../../assets/images/baby/all/181.png"),
//                    182:require("../../assets/images/baby/all/182.png"),
//                    183:require("../../assets/images/baby/all/183.png"),
//                    184:require("../../assets/images/baby/all/184.png"),
//                    185:require("../../assets/images/baby/all/185.png"),
//                    186:require("../../assets/images/baby/all/186.png"),
//                    187:require("../../assets/images/baby/all/187.png"),
//                    188:require("../../assets/images/baby/all/188.png"),
//                    189:require("../../assets/images/baby/all/189.png"),
//                    190:require("../../assets/images/baby/all/190.png"),
//                    191:require("../../assets/images/baby/all/191.png"),
//                    192:require("../../assets/images/baby/all/192.png"),
//                    193:require("../../assets/images/baby/all/193.png"),
//                    194:require("../../assets/images/baby/all/194.png"),
//                    195:require("../../assets/images/baby/all/195.png"),
//                    196:require("../../assets/images/baby/all/196.png"),
//                    197:require("../../assets/images/baby/all/197.png"),
//                    198:require("../../assets/images/baby/all/198.png"),
//                    199:require("../../assets/images/baby/all/199.png"),
//                    200:require("../../assets/images/baby/all/200.png"),
//                    201:require("../../assets/images/baby/all/201.png"),
//                    202:require("../../assets/images/baby/all/202.png"),
//                    203:require("../../assets/images/baby/all/203.png"),
//                    204:require("../../assets/images/baby/all/204.png"),
//                    205:require("../../assets/images/baby/all/205.png"),
//                    206:require("../../assets/images/baby/all/206.png"),
//                    207:require("../../assets/images/baby/all/207.png"),
//                    208:require("../../assets/images/baby/all/208.png"),
//                    209:require("../../assets/images/baby/all/209.png"),
//                    210:require("../../assets/images/baby/all/210.png"),
                    211:require("../../assets/images/baby/all/211.png"),
                    212:require("../../assets/images/baby/all/212.png"),
                    213:require("../../assets/images/baby/all/213.png"),
                    214:require("../../assets/images/baby/all/214.png"),
                    215:require("../../assets/images/baby/all/215.png"),
                    216:require("../../assets/images/baby/all/216.png"),
//                    217:require("../../assets/images/baby/all/217.png"),
//                    218:require("../../assets/images/baby/all/218.png"),
//                    219:require("../../assets/images/baby/all/219.png"),
//                    220:require("../../assets/images/baby/all/220.png"),
//                    221:require("../../assets/images/baby/all/221.png"),
//                    222:require("../../assets/images/baby/all/222.png"),
//                    223:require("../../assets/images/baby/all/223.png"),
//                    224:require("../../assets/images/baby/all/224.png"),
//                    225:require("../../assets/images/baby/all/225.png"),
//                    226:require("../../assets/images/baby/all/226.png"),
//                    227:require("../../assets/images/baby/all/227.png"),
//                    228:require("../../assets/images/baby/all/228.png"),
//                    229:require("../../assets/images/baby/all/229.png"),
//                    230:require("../../assets/images/baby/all/230.png"),
//                    231:require("../../assets/images/baby/all/231.png"),
//                    232:require("../../assets/images/baby/all/232.png"),
//                    233:require("../../assets/images/baby/all/233.png"),
//                    234:require("../../assets/images/baby/all/234.png"),
//                    235:require("../../assets/images/baby/all/235.png"),
//                    236:require("../../assets/images/baby/all/236.png"),
//                    237:require("../../assets/images/baby/all/237.png"),
//                    238:require("../../assets/images/baby/all/238.png"),
//                    239:require("../../assets/images/baby/all/239.png"),
//                    240:require("../../assets/images/baby/all/240.png"),
//                    241:require("../../assets/images/baby/all/241.png"),
//                    242:require("../../assets/images/baby/all/242.png"),
//                    243:require("../../assets/images/baby/all/243.png"),
//                    244:require("../../assets/images/baby/all/244.png"),
//                    245:require("../../assets/images/baby/all/245.png"),
//                    246:require("../../assets/images/baby/all/246.png"),
//                    247:require("../../assets/images/baby/all/247.png"),
//                    248:require("../../assets/images/baby/all/248.png"),
//                    249:require("../../assets/images/baby/all/249.png"),
//                    250:require("../../assets/images/baby/all/250.png"),
//                    251:require("../../assets/images/baby/all/251.png"),
//                    252:require("../../assets/images/baby/all/252.png"),
                    253:require("../../assets/images/baby/all/253.png"),
                    254:require("../../assets/images/baby/all/254.png"),
                    255:require("../../assets/images/baby/all/255.png"),
                    256:require("../../assets/images/baby/all/256.png"),
                    257:require("../../assets/images/baby/all/257.png"),
                    258:require("../../assets/images/baby/all/258.png"),
//                    259:require("../../assets/images/baby/all/259.png"),
//                    260:require("../../assets/images/baby/all/260.png"),
//                    261:require("../../assets/images/baby/all/261.png"),
//                    262:require("../../assets/images/baby/all/262.png"),
//                    263:require("../../assets/images/baby/all/263.png"),
//                    264:require("../../assets/images/baby/all/264.png"),
//                    265:require("../../assets/images/baby/all/265.png"),
//                    266:require("../../assets/images/baby/all/266.png"),
//                    267:require("../../assets/images/baby/all/267.png"),
//                    268:require("../../assets/images/baby/all/268.png"),
//                    269:require("../../assets/images/baby/all/269.png"),
//                    270:require("../../assets/images/baby/all/270.png"),
//                    271:require("../../assets/images/baby/all/271.png"),
//                    272:require("../../assets/images/baby/all/272.png"),
//                    273:require("../../assets/images/baby/all/273.png"),
//                    274:require("../../assets/images/baby/all/274.png"),
//                    275:require("../../assets/images/baby/all/275.png"),
//                    276:require("../../assets/images/baby/all/276.png"),
//                    277:require("../../assets/images/baby/all/277.png"),
//                    278:require("../../assets/images/baby/all/278.png"),
//                    279:require("../../assets/images/baby/all/279.png"),
//                    280:require("../../assets/images/baby/all/280.png"),
//                    281:require("../../assets/images/baby/all/281.png"),
//                    282:require("../../assets/images/baby/all/282.png"),
//                    283:require("../../assets/images/baby/all/283.png"),
//                    284:require("../../assets/images/baby/all/284.png"),
//                    285:require("../../assets/images/baby/all/285.png"),
//                    286:require("../../assets/images/baby/all/286.png"),
//                    287:require("../../assets/images/baby/all/287.png"),
//                    288:require("../../assets/images/baby/all/288.png"),
//                    289:require("../../assets/images/baby/all/289.png"),
//                    290:require("../../assets/images/baby/all/290.png"),
//                    291:require("../../assets/images/baby/all/291.png"),
//                    292:require("../../assets/images/baby/all/292.png"),
//                    293:require("../../assets/images/baby/all/293.png"),
//                    294:require("../../assets/images/baby/all/294.png"),
                    295:require("../../assets/images/baby/all/295.png"),
                    296:require("../../assets/images/baby/all/296.png"),
                    297:require("../../assets/images/baby/all/297.png"),
                    298:require("../../assets/images/baby/all/298.png"),
                    299:require("../../assets/images/baby/all/299.png"),
                    300:require("../../assets/images/baby/all/300.png"),
//                    301:require("../../assets/images/baby/all/301.png"),
//                    302:require("../../assets/images/baby/all/302.png"),
//                    303:require("../../assets/images/baby/all/303.png"),
//                    304:require("../../assets/images/baby/all/304.png"),
//                    305:require("../../assets/images/baby/all/305.png"),
//                    306:require("../../assets/images/baby/all/306.png"),
//                    307:require("../../assets/images/baby/all/307.png"),
//                    308:require("../../assets/images/baby/all/308.png"),
//                    309:require("../../assets/images/baby/all/309.png"),
//                    310:require("../../assets/images/baby/all/310.png"),
//                    311:require("../../assets/images/baby/all/311.png"),
//                    312:require("../../assets/images/baby/all/312.png"),
//                    313:require("../../assets/images/baby/all/313.png"),
//                    314:require("../../assets/images/baby/all/314.png"),
//                    315:require("../../assets/images/baby/all/315.png"),
//                    316:require("../../assets/images/baby/all/316.png"),
//                    317:require("../../assets/images/baby/all/317.png"),
//                    318:require("../../assets/images/baby/all/318.png"),
//                    319:require("../../assets/images/baby/all/319.png"),
//                    320:require("../../assets/images/baby/all/320.png"),
//                    321:require("../../assets/images/baby/all/321.png"),
//                    322:require("../../assets/images/baby/all/322.png"),
//                    323:require("../../assets/images/baby/all/323.png"),
//                    324:require("../../assets/images/baby/all/324.png"),
//                    325:require("../../assets/images/baby/all/325.png"),
//                    326:require("../../assets/images/baby/all/326.png"),
//                    327:require("../../assets/images/baby/all/327.png"),
//                    328:require("../../assets/images/baby/all/328.png"),
//                    329:require("../../assets/images/baby/all/329.png"),
//                    330:require("../../assets/images/baby/all/330.png"),
//                    331:require("../../assets/images/baby/all/331.png"),
//                    332:require("../../assets/images/baby/all/332.png"),
//                    333:require("../../assets/images/baby/all/333.png"),
//                    334:require("../../assets/images/baby/all/334.png"),
//                    335:require("../../assets/images/baby/all/335.png"),
//                    336:require("../../assets/images/baby/all/336.png"),
                    337:require("../../assets/images/baby/all/337.png"),
                    338:require("../../assets/images/baby/all/338.png"),
                    339:require("../../assets/images/baby/all/339.png"),
                    340:require("../../assets/images/baby/all/340.png"),
                    341:require("../../assets/images/baby/all/341.png"),
                    342:require("../../assets/images/baby/all/342.png"),
//                    343:require("../../assets/images/baby/all/343.png"),
//                    344:require("../../assets/images/baby/all/344.png"),
//                    345:require("../../assets/images/baby/all/345.png"),
//                    346:require("../../assets/images/baby/all/346.png"),
//                    347:require("../../assets/images/baby/all/347.png"),
//                    348:require("../../assets/images/baby/all/348.png"),
//                    349:require("../../assets/images/baby/all/349.png"),
//                    350:require("../../assets/images/baby/all/350.png"),
//                    351:require("../../assets/images/baby/all/351.png"),
//                    352:require("../../assets/images/baby/all/352.png"),
//                    353:require("../../assets/images/baby/all/353.png"),
//                    354:require("../../assets/images/baby/all/354.png"),
//                    355:require("../../assets/images/baby/all/355.png"),
//                    356:require("../../assets/images/baby/all/356.png"),
//                    357:require("../../assets/images/baby/all/357.png"),
//                    358:require("../../assets/images/baby/all/358.png"),
//                    359:require("../../assets/images/baby/all/359.png"),
//                    360:require("../../assets/images/baby/all/360.png"),
//                    361:require("../../assets/images/baby/all/361.png"),
//                    362:require("../../assets/images/baby/all/362.png"),
//                    363:require("../../assets/images/baby/all/363.png"),
//                    364:require("../../assets/images/baby/all/364.png"),
//                    365:require("../../assets/images/baby/all/365.png"),
//                    366:require("../../assets/images/baby/all/366.png"),
//                    367:require("../../assets/images/baby/all/367.png"),
//                    368:require("../../assets/images/baby/all/368.png"),
//                    369:require("../../assets/images/baby/all/369.png"),
//                    370:require("../../assets/images/baby/all/370.png"),
//                    371:require("../../assets/images/baby/all/371.png"),
//                    372:require("../../assets/images/baby/all/372.png"),
//                    373:require("../../assets/images/baby/all/373.png"),
//                    374:require("../../assets/images/baby/all/374.png"),
//                    375:require("../../assets/images/baby/all/375.png"),
//                    376:require("../../assets/images/baby/all/376.png"),
//                    377:require("../../assets/images/baby/all/377.png"),
//                    378:require("../../assets/images/baby/all/378.png"),
                    379:require("../../assets/images/baby/all/379.png"),
                    380:require("../../assets/images/baby/all/380.png"),
                    381:require("../../assets/images/baby/all/381.png"),
                    382:require("../../assets/images/baby/all/382.png"),
                    383:require("../../assets/images/baby/all/383.png"),
                    384:require("../../assets/images/baby/all/384.png"),
//                    385:require("../../assets/images/baby/all/385.png"),
//                    386:require("../../assets/images/baby/all/386.png"),
//                    387:require("../../assets/images/baby/all/387.png"),
//                    388:require("../../assets/images/baby/all/388.png"),
//                    389:require("../../assets/images/baby/all/389.png"),
//                    390:require("../../assets/images/baby/all/390.png"),
//                    391:require("../../assets/images/baby/all/391.png"),
//                    392:require("../../assets/images/baby/all/392.png"),
//                    393:require("../../assets/images/baby/all/393.png"),
//                    394:require("../../assets/images/baby/all/394.png"),
//                    395:require("../../assets/images/baby/all/395.png"),
//                    396:require("../../assets/images/baby/all/396.png"),
//                    397:require("../../assets/images/baby/all/397.png"),
//                    398:require("../../assets/images/baby/all/398.png"),
//                    399:require("../../assets/images/baby/all/399.png"),
//                    400:require("../../assets/images/baby/all/400.png"),
//                    401:require("../../assets/images/baby/all/401.png"),
//                    402:require("../../assets/images/baby/all/402.png"),
//                    403:require("../../assets/images/baby/all/403.png"),
//                    404:require("../../assets/images/baby/all/404.png"),
//                    405:require("../../assets/images/baby/all/405.png"),
//                    406:require("../../assets/images/baby/all/406.png"),
//                    407:require("../../assets/images/baby/all/407.png"),
//                    408:require("../../assets/images/baby/all/408.png"),
//                    409:require("../../assets/images/baby/all/409.png"),
//                    410:require("../../assets/images/baby/all/410.png"),
//                    411:require("../../assets/images/baby/all/411.png"),
//                    412:require("../../assets/images/baby/all/412.png"),
//                    413:require("../../assets/images/baby/all/413.png"),
//                    414:require("../../assets/images/baby/all/414.png"),
//                    415:require("../../assets/images/baby/all/415.png"),
//                    416:require("../../assets/images/baby/all/416.png"),
//                    417:require("../../assets/images/baby/all/417.png"),
//                    418:require("../../assets/images/baby/all/418.png"),
//                    419:require("../../assets/images/baby/all/419.png"),
//                    420:require("../../assets/images/baby/all/420.png"),
                    421:require("../../assets/images/baby/all/421.png"),
                    422:require("../../assets/images/baby/all/422.png"),
                    423:require("../../assets/images/baby/all/423.png"),
                    424:require("../../assets/images/baby/all/424.png"),
                    425:require("../../assets/images/baby/all/425.png"),
                    426:require("../../assets/images/baby/all/426.png"),
//                    427:require("../../assets/images/baby/all/427.png"),
//                    428:require("../../assets/images/baby/all/428.png"),
//                    429:require("../../assets/images/baby/all/429.png"),
//                    430:require("../../assets/images/baby/all/430.png"),
//                    431:require("../../assets/images/baby/all/431.png"),
//                    432:require("../../assets/images/baby/all/432.png"),
//                    433:require("../../assets/images/baby/all/433.png"),
//                    434:require("../../assets/images/baby/all/434.png"),
//                    435:require("../../assets/images/baby/all/435.png"),
//                    436:require("../../assets/images/baby/all/436.png"),
//                    437:require("../../assets/images/baby/all/437.png"),
//                    438:require("../../assets/images/baby/all/438.png"),
//                    439:require("../../assets/images/baby/all/439.png"),
//                    440:require("../../assets/images/baby/all/440.png"),
//                    441:require("../../assets/images/baby/all/441.png"),
//                    442:require("../../assets/images/baby/all/442.png"),
//                    443:require("../../assets/images/baby/all/443.png"),
//                    444:require("../../assets/images/baby/all/444.png"),
//                    445:require("../../assets/images/baby/all/445.png"),
//                    446:require("../../assets/images/baby/all/446.png"),
//                    447:require("../../assets/images/baby/all/447.png"),
//                    448:require("../../assets/images/baby/all/448.png"),
//                    449:require("../../assets/images/baby/all/449.png"),
//                    450:require("../../assets/images/baby/all/450.png"),
//                    451:require("../../assets/images/baby/all/451.png"),
//                    452:require("../../assets/images/baby/all/452.png"),
//                    453:require("../../assets/images/baby/all/453.png"),
//                    454:require("../../assets/images/baby/all/454.png"),
//                    455:require("../../assets/images/baby/all/455.png"),
//                    456:require("../../assets/images/baby/all/456.png"),
//                    457:require("../../assets/images/baby/all/457.png"),
//                    458:require("../../assets/images/baby/all/458.png"),
//                    459:require("../../assets/images/baby/all/459.png"),
//                    460:require("../../assets/images/baby/all/460.png"),
//                    461:require("../../assets/images/baby/all/461.png"),
//                    462:require("../../assets/images/baby/all/462.png"),
                    463:require("../../assets/images/baby/all/463.png"),
                    464:require("../../assets/images/baby/all/464.png"),
                    465:require("../../assets/images/baby/all/465.png"),
                    466:require("../../assets/images/baby/all/466.png"),
                    467:require("../../assets/images/baby/all/467.png"),
                    468:require("../../assets/images/baby/all/468.png"),
//                    469:require("../../assets/images/baby/all/469.png"),
//                    470:require("../../assets/images/baby/all/470.png"),
//                    471:require("../../assets/images/baby/all/471.png"),
//                    472:require("../../assets/images/baby/all/472.png"),
//                    473:require("../../assets/images/baby/all/473.png"),
//                    474:require("../../assets/images/baby/all/474.png"),
//                    475:require("../../assets/images/baby/all/475.png"),
//                    476:require("../../assets/images/baby/all/476.png"),
//                    477:require("../../assets/images/baby/all/477.png"),
//                    478:require("../../assets/images/baby/all/478.png"),
//                    479:require("../../assets/images/baby/all/479.png"),
//                    480:require("../../assets/images/baby/all/480.png"),
//                    481:require("../../assets/images/baby/all/481.png"),
//                    482:require("../../assets/images/baby/all/482.png"),
//                    483:require("../../assets/images/baby/all/483.png"),
//                    484:require("../../assets/images/baby/all/484.png"),
//                    485:require("../../assets/images/baby/all/485.png"),
//                    486:require("../../assets/images/baby/all/486.png"),
//                    487:require("../../assets/images/baby/all/487.png"),
//                    488:require("../../assets/images/baby/all/488.png"),
//                    489:require("../../assets/images/baby/all/489.png"),
//                    490:require("../../assets/images/baby/all/490.png"),
//                    491:require("../../assets/images/baby/all/491.png"),
//                    492:require("../../assets/images/baby/all/492.png"),
//                    493:require("../../assets/images/baby/all/493.png"),
//                    494:require("../../assets/images/baby/all/494.png"),
//                    495:require("../../assets/images/baby/all/495.png"),
//                    496:require("../../assets/images/baby/all/496.png"),
//                    497:require("../../assets/images/baby/all/497.png"),
//                    498:require("../../assets/images/baby/all/498.png"),
//                    499:require("../../assets/images/baby/all/499.png"),
//                    500:require("../../assets/images/baby/all/500.png"),
//                    501:require("../../assets/images/baby/all/501.png"),
//                    502:require("../../assets/images/baby/all/502.png"),
//                    503:require("../../assets/images/baby/all/503.png"),
//                    504:require("../../assets/images/baby/all/504.png"),
//                    505:require("../../assets/images/baby/all/505.png"),
//                    506:require("../../assets/images/baby/all/506.png"),
//                    507:require("../../assets/images/baby/all/507.png"),
//                    508:require("../../assets/images/baby/all/508.png"),
//                    509:require("../../assets/images/baby/all/509.png"),
//                    510:require("../../assets/images/baby/all/510.png"),
//                    511:require("../../assets/images/baby/all/511.png"),
//                    512:require("../../assets/images/baby/all/512.png"),
//                    513:require("../../assets/images/baby/all/513.png"),
//                    514:require("../../assets/images/baby/all/514.png"),
//                    515:require("../../assets/images/baby/all/515.png"),
//                    516:require("../../assets/images/baby/all/516.png"),
//                    517:require("../../assets/images/baby/all/517.png"),
//                    518:require("../../assets/images/baby/all/518.png"),
//                    519:require("../../assets/images/baby/all/519.png"),
//                    520:require("../../assets/images/baby/all/520.png"),
//                    521:require("../../assets/images/baby/all/521.png"),
//                    522:require("../../assets/images/baby/all/522.png"),
//                    523:require("../../assets/images/baby/all/523.png"),
//                    524:require("../../assets/images/baby/all/524.png"),
//                    525:require("../../assets/images/baby/all/525.png"),
//                    526:require("../../assets/images/baby/all/526.png"),
//                    527:require("../../assets/images/baby/all/527.png"),
//                    528:require("../../assets/images/baby/all/528.png"),
//                    529:require("../../assets/images/baby/all/529.png"),
//                    530:require("../../assets/images/baby/all/530.png"),
//                    531:require("../../assets/images/baby/all/531.png"),
//                    532:require("../../assets/images/baby/all/532.png"),
//                    533:require("../../assets/images/baby/all/533.png"),
//                    534:require("../../assets/images/baby/all/534.png"),
//                    535:require("../../assets/images/baby/all/535.png"),
//                    536:require("../../assets/images/baby/all/536.png"),
//                    537:require("../../assets/images/baby/all/537.png"),
//                    538:require("../../assets/images/baby/all/538.png"),
//                    539:require("../../assets/images/baby/all/539.png"),
//                    540:require("../../assets/images/baby/all/540.png"),
//                    541:require("../../assets/images/baby/all/541.png"),
//                    542:require("../../assets/images/baby/all/542.png"),
//                    543:require("../../assets/images/baby/all/543.png"),
//                    544:require("../../assets/images/baby/all/544.png"),
//                    545:require("../../assets/images/baby/all/545.png"),
//                    546:require("../../assets/images/baby/all/546.png")
                  };

                  if (images[responseData.avatarId]) {
                      setAvatarSource(images[responseData.avatarId]);
                  }
              } else {
                  console.error('後端返回的數據格式不符合預期');
              }
          } else {
              console.log('抓不到token');
          }
      } catch (error) {
          console.error('錯誤：獲取用戶數據', error);
      }
    }

  

    return () => {
        unsubscribe();  // 清理訂閱
    };
  }, [navigation]);

  return (
    <SafeAreaView style={styles.container}>
      <View style={[styles.rowContainer]}>
        <View style={styles.circle}>
          <Image style={styles.pic} source={avatarSource} />
        </View>
        <View>
          <Text>{userData.name}</Text>
          <Text>{userData.email}</Text>
        </View>
      </View>

      <View style={styles.m}>
        <View style={[styles.OutCol]}>
          <TouchableOpacity style={[styles.infoCol]} onPress={() => navigation.navigate("任務清單")}>
            <Ionicons name="person-circle-outline" size={50} color={'#C0C0C0'}/>
            <Text style={{fontSize:18,}}>個人資訊</Text>
          </TouchableOpacity>
          <TouchableOpacity style={[styles.infoCol]} onPress={() => navigation.navigate("任務清單")}>
            <Ionicons name="megaphone-outline" size={50} color={'#C0C0C0'}/>
            <Text style={{fontSize:18,}}>最新公告</Text>
          </TouchableOpacity>
        </View>
        
        <View style={[styles.OutCol]}>
            <TouchableOpacity style={[styles.infoCol]} onPress={() => navigation.navigate("我的收藏")}>
            <Ionicons name="heart-circle-outline" size={50} color={'#C0C0C0'}></Ionicons>
            <Text style={{fontSize:18,}}>我的收藏</Text></TouchableOpacity>
            <TouchableOpacity style={[styles.infoCol]} onPress={() => navigation.navigate("瀏覽紀錄")}>
            <Ionicons name="time-outline" size={50} color={'#C0C0C0'}></Ionicons>
            <Text style={{fontSize:18,}}>瀏覽紀錄</Text></TouchableOpacity>
        </View>

        <View style={[styles.OutCol]}>
            <TouchableOpacity style={[styles.infoCol]}>
            <Ionicons name="document-text-outline" size={50} color={'#C0C0C0'}></Ionicons>
            <Text style={{fontSize:18,}}>隱私政策與條款</Text></TouchableOpacity>
            <TouchableOpacity style={[styles.infoCol]}>
            <Ionicons name="help-circle-outline" size={50} color={'#C0C0C0'}></Ionicons>
            <Text style={{fontSize:18,}}>常見問題與說明</Text></TouchableOpacity>
        </View>   
          
        <View style={[globalStyles.Gocenter, {padding:50}]}>
            <TouchableOpacity style={[styles.logout,]} /*onPress={() => navigation.navigate('')}*/>
                <Ionicons name="log-out-outline" size={30} color={'#c13e27'}></Ionicons>
                <Text style={[styles.logOutBtn,]}>登出 </Text>
            </TouchableOpacity>
        </View>
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  logOutBtn:{
    color: '#c13e27',
    fontSize: 18,
  },
  rowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding:10,
    borderRadius:10,
    backgroundColor:'white',
    width:"95%",
    marginLeft:10,
    marginTop:30,
  },
  circle: {
    width: 96,
    height: 96,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#777',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  pic:{
    width:92,
    height:92,
    resizeMode:'contain',
  },
  OutCol:{
    flexDirection:'row',
    justifyContent:'space-around',
  },
  infoCol: {
    borderRadius:20,
    width:"45%",
    backgroundColor:'white',
    marginBottom: 10,//框外距離
    marginVertical: 5,//第一個框到最上面的距離
    padding:10,
    height:100,
    justifyContent:'center',
    alignContent:'center',
    alignItems:'center',
  },
  m:{marginTop:30,padding:10,justifyContent:'space-between'},
  logout:{
    borderBottomWidth:3,
    padding:5,
    borderBottomColor:'#c13e27',
    flexDirection:'row',
    justifyContent:'center',
    alignItems:'center',
  }
});
