# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class UidRestaurant(models.Model):
    uid = models.AutoField(db_column='uID', primary_key=True)  # Field name made lowercase.
    number_4 = models.IntegerField(db_column='4', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_5 = models.IntegerField(db_column='5', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_6 = models.IntegerField(db_column='6', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_8 = models.IntegerField(db_column='8', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_9 = models.IntegerField(db_column='9', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_10 = models.IntegerField(db_column='10', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_11 = models.IntegerField(db_column='11', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_12 = models.IntegerField(db_column='12', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_14 = models.IntegerField(db_column='14', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_15 = models.IntegerField(db_column='15', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_16 = models.IntegerField(db_column='16', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_17 = models.IntegerField(db_column='17', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_18 = models.IntegerField(db_column='18', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_19 = models.IntegerField(db_column='19', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_20 = models.IntegerField(db_column='20', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_21 = models.IntegerField(db_column='21', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_22 = models.IntegerField(db_column='22', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_23 = models.IntegerField(db_column='23', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_24 = models.IntegerField(db_column='24', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_25 = models.IntegerField(db_column='25', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_26 = models.IntegerField(db_column='26', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_27 = models.IntegerField(db_column='27', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_28 = models.IntegerField(db_column='28', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_29 = models.IntegerField(db_column='29', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_30 = models.IntegerField(db_column='30', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_31 = models.IntegerField(db_column='31', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_32 = models.IntegerField(db_column='32', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_33 = models.IntegerField(db_column='33', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_34 = models.IntegerField(db_column='34', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_35 = models.IntegerField(db_column='35', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_36 = models.IntegerField(db_column='36', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_37 = models.IntegerField(db_column='37', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_39 = models.IntegerField(db_column='39', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_40 = models.IntegerField(db_column='40', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_41 = models.IntegerField(db_column='41', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_42 = models.IntegerField(db_column='42', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_43 = models.IntegerField(db_column='43', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_44 = models.IntegerField(db_column='44', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_45 = models.IntegerField(db_column='45', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_46 = models.IntegerField(db_column='46', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_47 = models.IntegerField(db_column='47', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_48 = models.IntegerField(db_column='48', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_49 = models.IntegerField(db_column='49', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_50 = models.IntegerField(db_column='50', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_51 = models.IntegerField(db_column='51', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_52 = models.IntegerField(db_column='52', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_54 = models.IntegerField(db_column='54', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_55 = models.IntegerField(db_column='55', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_56 = models.IntegerField(db_column='56', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_57 = models.IntegerField(db_column='57', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_58 = models.IntegerField(db_column='58', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_59 = models.IntegerField(db_column='59', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_60 = models.IntegerField(db_column='60', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_61 = models.IntegerField(db_column='61', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_62 = models.IntegerField(db_column='62', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_63 = models.IntegerField(db_column='63', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_64 = models.IntegerField(db_column='64', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_65 = models.IntegerField(db_column='65', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_66 = models.IntegerField(db_column='66', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_67 = models.IntegerField(db_column='67', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_68 = models.IntegerField(db_column='68', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_69 = models.IntegerField(db_column='69', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_70 = models.IntegerField(db_column='70', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_72 = models.IntegerField(db_column='72', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_73 = models.IntegerField(db_column='73', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_74 = models.IntegerField(db_column='74', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_75 = models.IntegerField(db_column='75', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_76 = models.IntegerField(db_column='76', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_77 = models.IntegerField(db_column='77', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_78 = models.IntegerField(db_column='78', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_79 = models.IntegerField(db_column='79', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_80 = models.IntegerField(db_column='80', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_81 = models.IntegerField(db_column='81', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_82 = models.IntegerField(db_column='82', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_83 = models.IntegerField(db_column='83', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_84 = models.IntegerField(db_column='84', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_86 = models.IntegerField(db_column='86', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_87 = models.IntegerField(db_column='87', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_88 = models.IntegerField(db_column='88', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_89 = models.IntegerField(db_column='89', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_90 = models.IntegerField(db_column='90', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_91 = models.IntegerField(db_column='91', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_92 = models.IntegerField(db_column='92', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_93 = models.IntegerField(db_column='93', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_94 = models.IntegerField(db_column='94', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_95 = models.IntegerField(db_column='95', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_96 = models.IntegerField(db_column='96', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_97 = models.IntegerField(db_column='97', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_98 = models.IntegerField(db_column='98', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_99 = models.IntegerField(db_column='99', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_100 = models.IntegerField(db_column='100', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_101 = models.IntegerField(db_column='101', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_102 = models.IntegerField(db_column='102', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_103 = models.IntegerField(db_column='103', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_104 = models.IntegerField(db_column='104', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_105 = models.IntegerField(db_column='105', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_106 = models.IntegerField(db_column='106', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_107 = models.IntegerField(db_column='107', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_108 = models.IntegerField(db_column='108', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_109 = models.IntegerField(db_column='109', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_110 = models.IntegerField(db_column='110', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_111 = models.IntegerField(db_column='111', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_112 = models.IntegerField(db_column='112', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_113 = models.IntegerField(db_column='113', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_114 = models.IntegerField(db_column='114', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_115 = models.IntegerField(db_column='115', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_116 = models.IntegerField(db_column='116', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_117 = models.IntegerField(db_column='117', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_118 = models.IntegerField(db_column='118', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_119 = models.IntegerField(db_column='119', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_120 = models.IntegerField(db_column='120', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_121 = models.IntegerField(db_column='121', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_122 = models.IntegerField(db_column='122', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_123 = models.IntegerField(db_column='123', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_124 = models.IntegerField(db_column='124', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_125 = models.IntegerField(db_column='125', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_126 = models.IntegerField(db_column='126', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_127 = models.IntegerField(db_column='127', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_128 = models.IntegerField(db_column='128', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_129 = models.IntegerField(db_column='129', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_130 = models.IntegerField(db_column='130', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_131 = models.IntegerField(db_column='131', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_132 = models.IntegerField(db_column='132', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_133 = models.IntegerField(db_column='133', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_134 = models.IntegerField(db_column='134', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_135 = models.IntegerField(db_column='135', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_136 = models.IntegerField(db_column='136', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_137 = models.IntegerField(db_column='137', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_138 = models.IntegerField(db_column='138', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_139 = models.IntegerField(db_column='139', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_140 = models.IntegerField(db_column='140', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_141 = models.IntegerField(db_column='141', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_142 = models.IntegerField(db_column='142', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_143 = models.IntegerField(db_column='143', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_144 = models.IntegerField(db_column='144', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_145 = models.IntegerField(db_column='145', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_146 = models.IntegerField(db_column='146', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_147 = models.IntegerField(db_column='147', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_149 = models.IntegerField(db_column='149', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_150 = models.IntegerField(db_column='150', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_151 = models.IntegerField(db_column='151', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_152 = models.IntegerField(db_column='152', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_153 = models.IntegerField(db_column='153', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_155 = models.IntegerField(db_column='155', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_157 = models.IntegerField(db_column='157', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_158 = models.IntegerField(db_column='158', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_159 = models.IntegerField(db_column='159', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_160 = models.IntegerField(db_column='160', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_161 = models.IntegerField(db_column='161', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_162 = models.IntegerField(db_column='162', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_163 = models.IntegerField(db_column='163', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_164 = models.IntegerField(db_column='164', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_165 = models.IntegerField(db_column='165', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_166 = models.IntegerField(db_column='166', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_167 = models.IntegerField(db_column='167', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_168 = models.IntegerField(db_column='168', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_169 = models.IntegerField(db_column='169', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_170 = models.IntegerField(db_column='170', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_171 = models.IntegerField(db_column='171', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_172 = models.IntegerField(db_column='172', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_173 = models.IntegerField(db_column='173', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_174 = models.IntegerField(db_column='174', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_175 = models.IntegerField(db_column='175', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_176 = models.IntegerField(db_column='176', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_177 = models.IntegerField(db_column='177', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_178 = models.IntegerField(db_column='178', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_179 = models.IntegerField(db_column='179', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_180 = models.IntegerField(db_column='180', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_181 = models.IntegerField(db_column='181', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_182 = models.IntegerField(db_column='182', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_183 = models.IntegerField(db_column='183', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_184 = models.IntegerField(db_column='184', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_185 = models.IntegerField(db_column='185', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_186 = models.IntegerField(db_column='186', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_187 = models.IntegerField(db_column='187', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_188 = models.IntegerField(db_column='188', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_189 = models.IntegerField(db_column='189', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_190 = models.IntegerField(db_column='190', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_191 = models.IntegerField(db_column='191', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_192 = models.IntegerField(db_column='192', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_193 = models.IntegerField(db_column='193', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_194 = models.IntegerField(db_column='194', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_195 = models.IntegerField(db_column='195', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_196 = models.IntegerField(db_column='196', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_198 = models.IntegerField(db_column='198', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_199 = models.IntegerField(db_column='199', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_200 = models.IntegerField(db_column='200', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_201 = models.IntegerField(db_column='201', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_202 = models.IntegerField(db_column='202', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_203 = models.IntegerField(db_column='203', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_204 = models.IntegerField(db_column='204', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_205 = models.IntegerField(db_column='205', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_206 = models.IntegerField(db_column='206', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_207 = models.IntegerField(db_column='207', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_208 = models.IntegerField(db_column='208', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_210 = models.IntegerField(db_column='210', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_211 = models.IntegerField(db_column='211', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_212 = models.IntegerField(db_column='212', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_213 = models.IntegerField(db_column='213', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_214 = models.IntegerField(db_column='214', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_215 = models.IntegerField(db_column='215', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_216 = models.IntegerField(db_column='216', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_217 = models.IntegerField(db_column='217', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_218 = models.IntegerField(db_column='218', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_219 = models.IntegerField(db_column='219', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_220 = models.IntegerField(db_column='220', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_222 = models.IntegerField(db_column='222', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_223 = models.IntegerField(db_column='223', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_224 = models.IntegerField(db_column='224', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_225 = models.IntegerField(db_column='225', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_227 = models.IntegerField(db_column='227', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_228 = models.IntegerField(db_column='228', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_229 = models.IntegerField(db_column='229', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_230 = models.IntegerField(db_column='230', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_231 = models.IntegerField(db_column='231', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_232 = models.IntegerField(db_column='232', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_233 = models.IntegerField(db_column='233', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_234 = models.IntegerField(db_column='234', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_235 = models.IntegerField(db_column='235', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_236 = models.IntegerField(db_column='236', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_237 = models.IntegerField(db_column='237', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_238 = models.IntegerField(db_column='238', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_239 = models.IntegerField(db_column='239', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_241 = models.IntegerField(db_column='241', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_242 = models.IntegerField(db_column='242', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_243 = models.IntegerField(db_column='243', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_244 = models.IntegerField(db_column='244', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_245 = models.IntegerField(db_column='245', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_246 = models.IntegerField(db_column='246', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_247 = models.IntegerField(db_column='247', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_248 = models.IntegerField(db_column='248', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_249 = models.IntegerField(db_column='249', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_250 = models.IntegerField(db_column='250', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_251 = models.IntegerField(db_column='251', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_252 = models.IntegerField(db_column='252', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_253 = models.IntegerField(db_column='253', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_254 = models.IntegerField(db_column='254', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_255 = models.IntegerField(db_column='255', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_256 = models.IntegerField(db_column='256', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_257 = models.IntegerField(db_column='257', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_260 = models.IntegerField(db_column='260', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_261 = models.IntegerField(db_column='261', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_263 = models.IntegerField(db_column='263', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_264 = models.IntegerField(db_column='264', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_265 = models.IntegerField(db_column='265', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_266 = models.IntegerField(db_column='266', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_267 = models.IntegerField(db_column='267', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_269 = models.IntegerField(db_column='269', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_270 = models.IntegerField(db_column='270', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_271 = models.IntegerField(db_column='271', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_272 = models.IntegerField(db_column='272', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_273 = models.IntegerField(db_column='273', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_274 = models.IntegerField(db_column='274', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_275 = models.IntegerField(db_column='275', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_276 = models.IntegerField(db_column='276', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_277 = models.IntegerField(db_column='277', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_278 = models.IntegerField(db_column='278', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_279 = models.IntegerField(db_column='279', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_280 = models.IntegerField(db_column='280', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_281 = models.IntegerField(db_column='281', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_282 = models.IntegerField(db_column='282', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_283 = models.IntegerField(db_column='283', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_284 = models.IntegerField(db_column='284', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_286 = models.IntegerField(db_column='286', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_287 = models.IntegerField(db_column='287', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_288 = models.IntegerField(db_column='288', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_289 = models.IntegerField(db_column='289', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_290 = models.IntegerField(db_column='290', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_291 = models.IntegerField(db_column='291', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_292 = models.IntegerField(db_column='292', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_293 = models.IntegerField(db_column='293', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_294 = models.IntegerField(db_column='294', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_295 = models.IntegerField(db_column='295', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_296 = models.IntegerField(db_column='296', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_297 = models.IntegerField(db_column='297', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_298 = models.IntegerField(db_column='298', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_299 = models.IntegerField(db_column='299', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_300 = models.IntegerField(db_column='300', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_301 = models.IntegerField(db_column='301', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_302 = models.IntegerField(db_column='302', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_303 = models.IntegerField(db_column='303', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_304 = models.IntegerField(db_column='304', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_305 = models.IntegerField(db_column='305', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_306 = models.IntegerField(db_column='306', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_307 = models.IntegerField(db_column='307', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_309 = models.IntegerField(db_column='309', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_310 = models.IntegerField(db_column='310', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_311 = models.IntegerField(db_column='311', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_312 = models.IntegerField(db_column='312', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_313 = models.IntegerField(db_column='313', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_314 = models.IntegerField(db_column='314', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_315 = models.IntegerField(db_column='315', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_316 = models.IntegerField(db_column='316', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_317 = models.IntegerField(db_column='317', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_318 = models.IntegerField(db_column='318', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_319 = models.IntegerField(db_column='319', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_320 = models.IntegerField(db_column='320', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_321 = models.IntegerField(db_column='321', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_322 = models.IntegerField(db_column='322', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_323 = models.IntegerField(db_column='323', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_324 = models.IntegerField(db_column='324', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_325 = models.IntegerField(db_column='325', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_326 = models.IntegerField(db_column='326', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_327 = models.IntegerField(db_column='327', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_328 = models.IntegerField(db_column='328', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_329 = models.IntegerField(db_column='329', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_330 = models.IntegerField(db_column='330', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_331 = models.IntegerField(db_column='331', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_332 = models.IntegerField(db_column='332', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_333 = models.IntegerField(db_column='333', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_334 = models.IntegerField(db_column='334', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_335 = models.IntegerField(db_column='335', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_336 = models.IntegerField(db_column='336', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_337 = models.IntegerField(db_column='337', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_338 = models.IntegerField(db_column='338', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_339 = models.IntegerField(db_column='339', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_340 = models.IntegerField(db_column='340', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_341 = models.IntegerField(db_column='341', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_342 = models.IntegerField(db_column='342', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_344 = models.IntegerField(db_column='344', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_345 = models.IntegerField(db_column='345', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_346 = models.IntegerField(db_column='346', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_347 = models.IntegerField(db_column='347', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_348 = models.IntegerField(db_column='348', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_349 = models.IntegerField(db_column='349', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_350 = models.IntegerField(db_column='350', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_351 = models.IntegerField(db_column='351', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_352 = models.IntegerField(db_column='352', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_353 = models.IntegerField(db_column='353', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_354 = models.IntegerField(db_column='354', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_355 = models.IntegerField(db_column='355', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_356 = models.IntegerField(db_column='356', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_357 = models.IntegerField(db_column='357', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_359 = models.IntegerField(db_column='359', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_360 = models.IntegerField(db_column='360', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_361 = models.IntegerField(db_column='361', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_362 = models.IntegerField(db_column='362', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_363 = models.IntegerField(db_column='363', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_364 = models.IntegerField(db_column='364', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_365 = models.IntegerField(db_column='365', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_366 = models.IntegerField(db_column='366', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_368 = models.IntegerField(db_column='368', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_369 = models.IntegerField(db_column='369', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_370 = models.IntegerField(db_column='370', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_372 = models.IntegerField(db_column='372', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_373 = models.IntegerField(db_column='373', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_374 = models.IntegerField(db_column='374', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_375 = models.IntegerField(db_column='375', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_376 = models.IntegerField(db_column='376', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_377 = models.IntegerField(db_column='377', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_378 = models.IntegerField(db_column='378', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_379 = models.IntegerField(db_column='379', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_380 = models.IntegerField(db_column='380', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_381 = models.IntegerField(db_column='381', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_382 = models.IntegerField(db_column='382', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_383 = models.IntegerField(db_column='383', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_384 = models.IntegerField(db_column='384', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_385 = models.IntegerField(db_column='385', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_386 = models.IntegerField(db_column='386', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_387 = models.IntegerField(db_column='387', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_388 = models.IntegerField(db_column='388', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_389 = models.IntegerField(db_column='389', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_390 = models.IntegerField(db_column='390', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_391 = models.IntegerField(db_column='391', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_392 = models.IntegerField(db_column='392', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_393 = models.IntegerField(db_column='393', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_394 = models.IntegerField(db_column='394', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_395 = models.IntegerField(db_column='395', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_396 = models.IntegerField(db_column='396', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_397 = models.IntegerField(db_column='397', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_398 = models.IntegerField(db_column='398', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_399 = models.IntegerField(db_column='399', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_400 = models.IntegerField(db_column='400', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_401 = models.IntegerField(db_column='401', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_402 = models.IntegerField(db_column='402', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_403 = models.IntegerField(db_column='403', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_404 = models.IntegerField(db_column='404', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_405 = models.IntegerField(db_column='405', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_406 = models.IntegerField(db_column='406', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_408 = models.IntegerField(db_column='408', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_409 = models.IntegerField(db_column='409', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_410 = models.IntegerField(db_column='410', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_411 = models.IntegerField(db_column='411', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_412 = models.IntegerField(db_column='412', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_413 = models.IntegerField(db_column='413', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_414 = models.IntegerField(db_column='414', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_415 = models.IntegerField(db_column='415', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_416 = models.IntegerField(db_column='416', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_417 = models.IntegerField(db_column='417', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_418 = models.IntegerField(db_column='418', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_419 = models.IntegerField(db_column='419', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_420 = models.IntegerField(db_column='420', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_421 = models.IntegerField(db_column='421', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_422 = models.IntegerField(db_column='422', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_423 = models.IntegerField(db_column='423', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_424 = models.IntegerField(db_column='424', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_425 = models.IntegerField(db_column='425', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_426 = models.IntegerField(db_column='426', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_427 = models.IntegerField(db_column='427', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_428 = models.IntegerField(db_column='428', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_429 = models.IntegerField(db_column='429', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_430 = models.IntegerField(db_column='430', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_431 = models.IntegerField(db_column='431', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_432 = models.IntegerField(db_column='432', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_433 = models.IntegerField(db_column='433', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_434 = models.IntegerField(db_column='434', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_435 = models.IntegerField(db_column='435', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_436 = models.IntegerField(db_column='436', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_437 = models.IntegerField(db_column='437', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_438 = models.IntegerField(db_column='438', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_439 = models.IntegerField(db_column='439', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_440 = models.IntegerField(db_column='440', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_441 = models.IntegerField(db_column='441', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_442 = models.IntegerField(db_column='442', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_443 = models.IntegerField(db_column='443', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_444 = models.IntegerField(db_column='444', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_445 = models.IntegerField(db_column='445', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_446 = models.IntegerField(db_column='446', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_447 = models.IntegerField(db_column='447', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_448 = models.IntegerField(db_column='448', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_449 = models.IntegerField(db_column='449', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_450 = models.IntegerField(db_column='450', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_451 = models.IntegerField(db_column='451', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_452 = models.IntegerField(db_column='452', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_454 = models.IntegerField(db_column='454', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_455 = models.IntegerField(db_column='455', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_456 = models.IntegerField(db_column='456', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_457 = models.IntegerField(db_column='457', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_458 = models.IntegerField(db_column='458', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_459 = models.IntegerField(db_column='459', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_460 = models.IntegerField(db_column='460', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_461 = models.IntegerField(db_column='461', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_462 = models.IntegerField(db_column='462', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_463 = models.IntegerField(db_column='463', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_464 = models.IntegerField(db_column='464', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_465 = models.IntegerField(db_column='465', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_466 = models.IntegerField(db_column='466', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_467 = models.IntegerField(db_column='467', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_468 = models.IntegerField(db_column='468', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_469 = models.IntegerField(db_column='469', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_470 = models.IntegerField(db_column='470', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_472 = models.IntegerField(db_column='472', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_473 = models.IntegerField(db_column='473', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_474 = models.IntegerField(db_column='474', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_475 = models.IntegerField(db_column='475', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_476 = models.IntegerField(db_column='476', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_477 = models.IntegerField(db_column='477', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_478 = models.IntegerField(db_column='478', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_479 = models.IntegerField(db_column='479', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_480 = models.IntegerField(db_column='480', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_481 = models.IntegerField(db_column='481', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_482 = models.IntegerField(db_column='482', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_483 = models.IntegerField(db_column='483', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_484 = models.IntegerField(db_column='484', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_485 = models.IntegerField(db_column='485', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_486 = models.IntegerField(db_column='486', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_487 = models.IntegerField(db_column='487', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_488 = models.IntegerField(db_column='488', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_489 = models.IntegerField(db_column='489', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_490 = models.IntegerField(db_column='490', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_491 = models.IntegerField(db_column='491', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_492 = models.IntegerField(db_column='492', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_493 = models.IntegerField(db_column='493', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_494 = models.IntegerField(db_column='494', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_495 = models.IntegerField(db_column='495', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_496 = models.IntegerField(db_column='496', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_497 = models.IntegerField(db_column='497', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_498 = models.IntegerField(db_column='498', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_499 = models.IntegerField(db_column='499', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_500 = models.IntegerField(db_column='500', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_501 = models.IntegerField(db_column='501', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_502 = models.IntegerField(db_column='502', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_503 = models.IntegerField(db_column='503', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_504 = models.IntegerField(db_column='504', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_505 = models.IntegerField(db_column='505', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_506 = models.IntegerField(db_column='506', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_507 = models.IntegerField(db_column='507', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_508 = models.IntegerField(db_column='508', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_509 = models.IntegerField(db_column='509', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_510 = models.IntegerField(db_column='510', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_511 = models.IntegerField(db_column='511', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_512 = models.IntegerField(db_column='512', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_513 = models.IntegerField(db_column='513', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_514 = models.IntegerField(db_column='514', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_515 = models.IntegerField(db_column='515', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_516 = models.IntegerField(db_column='516', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_517 = models.IntegerField(db_column='517', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_518 = models.IntegerField(db_column='518', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_519 = models.IntegerField(db_column='519', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_520 = models.IntegerField(db_column='520', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_521 = models.IntegerField(db_column='521', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_522 = models.IntegerField(db_column='522', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_523 = models.IntegerField(db_column='523', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_524 = models.IntegerField(db_column='524', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_525 = models.IntegerField(db_column='525', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_526 = models.IntegerField(db_column='526', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_527 = models.IntegerField(db_column='527', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_528 = models.IntegerField(db_column='528', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_529 = models.IntegerField(db_column='529', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_530 = models.IntegerField(db_column='530', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_531 = models.IntegerField(db_column='531', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_532 = models.IntegerField(db_column='532', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_533 = models.IntegerField(db_column='533', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_534 = models.IntegerField(db_column='534', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_536 = models.IntegerField(db_column='536', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_537 = models.IntegerField(db_column='537', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_538 = models.IntegerField(db_column='538', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_539 = models.IntegerField(db_column='539', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_540 = models.IntegerField(db_column='540', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_541 = models.IntegerField(db_column='541', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_542 = models.IntegerField(db_column='542', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_544 = models.IntegerField(db_column='544', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_545 = models.IntegerField(db_column='545', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_546 = models.IntegerField(db_column='546', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_547 = models.IntegerField(db_column='547', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_548 = models.IntegerField(db_column='548', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_549 = models.IntegerField(db_column='549', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_550 = models.IntegerField(db_column='550', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_551 = models.IntegerField(db_column='551', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_552 = models.IntegerField(db_column='552', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_553 = models.IntegerField(db_column='553', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_554 = models.IntegerField(db_column='554', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_555 = models.IntegerField(db_column='555', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_556 = models.IntegerField(db_column='556', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_557 = models.IntegerField(db_column='557', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_558 = models.IntegerField(db_column='558', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_559 = models.IntegerField(db_column='559', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_560 = models.IntegerField(db_column='560', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_564 = models.IntegerField(db_column='564', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_565 = models.IntegerField(db_column='565', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_566 = models.IntegerField(db_column='566', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_567 = models.IntegerField(db_column='567', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_568 = models.IntegerField(db_column='568', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_569 = models.IntegerField(db_column='569', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_570 = models.IntegerField(db_column='570', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_571 = models.IntegerField(db_column='571', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_572 = models.IntegerField(db_column='572', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_573 = models.IntegerField(db_column='573', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_575 = models.IntegerField(db_column='575', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_576 = models.IntegerField(db_column='576', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_577 = models.IntegerField(db_column='577', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_579 = models.IntegerField(db_column='579', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_581 = models.IntegerField(db_column='581', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_582 = models.IntegerField(db_column='582', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_583 = models.IntegerField(db_column='583', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_584 = models.IntegerField(db_column='584', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_585 = models.IntegerField(db_column='585', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_586 = models.IntegerField(db_column='586', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_587 = models.IntegerField(db_column='587', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_588 = models.IntegerField(db_column='588', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_590 = models.IntegerField(db_column='590', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_592 = models.IntegerField(db_column='592', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_593 = models.IntegerField(db_column='593', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_594 = models.IntegerField(db_column='594', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_595 = models.IntegerField(db_column='595', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_596 = models.IntegerField(db_column='596', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_597 = models.IntegerField(db_column='597', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_598 = models.IntegerField(db_column='598', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_599 = models.IntegerField(db_column='599', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_600 = models.IntegerField(db_column='600', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_601 = models.IntegerField(db_column='601', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_602 = models.IntegerField(db_column='602', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_603 = models.IntegerField(db_column='603', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_605 = models.IntegerField(db_column='605', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_607 = models.IntegerField(db_column='607', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_608 = models.IntegerField(db_column='608', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_609 = models.IntegerField(db_column='609', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_610 = models.IntegerField(db_column='610', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_611 = models.IntegerField(db_column='611', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_612 = models.IntegerField(db_column='612', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_613 = models.IntegerField(db_column='613', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_614 = models.IntegerField(db_column='614', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_615 = models.IntegerField(db_column='615', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_616 = models.IntegerField(db_column='616', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_618 = models.IntegerField(db_column='618', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_619 = models.IntegerField(db_column='619', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_620 = models.IntegerField(db_column='620', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_622 = models.IntegerField(db_column='622', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_623 = models.IntegerField(db_column='623', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_624 = models.IntegerField(db_column='624', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_625 = models.IntegerField(db_column='625', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_626 = models.IntegerField(db_column='626', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_628 = models.IntegerField(db_column='628', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_630 = models.IntegerField(db_column='630', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_632 = models.IntegerField(db_column='632', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_633 = models.IntegerField(db_column='633', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_634 = models.IntegerField(db_column='634', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_635 = models.IntegerField(db_column='635', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_636 = models.IntegerField(db_column='636', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_637 = models.IntegerField(db_column='637', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_638 = models.IntegerField(db_column='638', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_639 = models.IntegerField(db_column='639', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_640 = models.IntegerField(db_column='640', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_641 = models.IntegerField(db_column='641', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_643 = models.IntegerField(db_column='643', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_644 = models.IntegerField(db_column='644', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_645 = models.IntegerField(db_column='645', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_646 = models.IntegerField(db_column='646', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_647 = models.IntegerField(db_column='647', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_648 = models.IntegerField(db_column='648', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_649 = models.IntegerField(db_column='649', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_650 = models.IntegerField(db_column='650', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_651 = models.IntegerField(db_column='651', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_652 = models.IntegerField(db_column='652', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_653 = models.IntegerField(db_column='653', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_654 = models.IntegerField(db_column='654', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_655 = models.IntegerField(db_column='655', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_656 = models.IntegerField(db_column='656', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_657 = models.IntegerField(db_column='657', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_658 = models.IntegerField(db_column='658', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_659 = models.IntegerField(db_column='659', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_660 = models.IntegerField(db_column='660', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_661 = models.IntegerField(db_column='661', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_662 = models.IntegerField(db_column='662', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_663 = models.IntegerField(db_column='663', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_664 = models.IntegerField(db_column='664', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_665 = models.IntegerField(db_column='665', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_666 = models.IntegerField(db_column='666', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_667 = models.IntegerField(db_column='667', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_669 = models.IntegerField(db_column='669', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_670 = models.IntegerField(db_column='670', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_671 = models.IntegerField(db_column='671', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_673 = models.IntegerField(db_column='673', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_674 = models.IntegerField(db_column='674', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_675 = models.IntegerField(db_column='675', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_676 = models.IntegerField(db_column='676', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_677 = models.IntegerField(db_column='677', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_678 = models.IntegerField(db_column='678', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_680 = models.IntegerField(db_column='680', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_681 = models.IntegerField(db_column='681', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_682 = models.IntegerField(db_column='682', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_683 = models.IntegerField(db_column='683', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_684 = models.IntegerField(db_column='684', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_685 = models.IntegerField(db_column='685', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_686 = models.IntegerField(db_column='686', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_687 = models.IntegerField(db_column='687', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_688 = models.IntegerField(db_column='688', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_689 = models.IntegerField(db_column='689', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_690 = models.IntegerField(db_column='690', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_691 = models.IntegerField(db_column='691', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_692 = models.IntegerField(db_column='692', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_693 = models.IntegerField(db_column='693', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_694 = models.IntegerField(db_column='694', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_695 = models.IntegerField(db_column='695', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_696 = models.IntegerField(db_column='696', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_697 = models.IntegerField(db_column='697', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_698 = models.IntegerField(db_column='698', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_699 = models.IntegerField(db_column='699', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_700 = models.IntegerField(db_column='700', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_701 = models.IntegerField(db_column='701', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_702 = models.IntegerField(db_column='702', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_703 = models.IntegerField(db_column='703', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_704 = models.IntegerField(db_column='704', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_706 = models.IntegerField(db_column='706', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_707 = models.IntegerField(db_column='707', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_710 = models.IntegerField(db_column='710', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_711 = models.IntegerField(db_column='711', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_712 = models.IntegerField(db_column='712', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_713 = models.IntegerField(db_column='713', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_714 = models.IntegerField(db_column='714', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_715 = models.IntegerField(db_column='715', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_716 = models.IntegerField(db_column='716', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_717 = models.IntegerField(db_column='717', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_718 = models.IntegerField(db_column='718', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_720 = models.IntegerField(db_column='720', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_721 = models.IntegerField(db_column='721', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_722 = models.IntegerField(db_column='722', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_723 = models.IntegerField(db_column='723', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_724 = models.IntegerField(db_column='724', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_725 = models.IntegerField(db_column='725', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_726 = models.IntegerField(db_column='726', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_727 = models.IntegerField(db_column='727', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_728 = models.IntegerField(db_column='728', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_730 = models.IntegerField(db_column='730', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_732 = models.IntegerField(db_column='732', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_733 = models.IntegerField(db_column='733', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_734 = models.IntegerField(db_column='734', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_735 = models.IntegerField(db_column='735', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_736 = models.IntegerField(db_column='736', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_737 = models.IntegerField(db_column='737', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_739 = models.IntegerField(db_column='739', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_740 = models.IntegerField(db_column='740', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_741 = models.IntegerField(db_column='741', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_742 = models.IntegerField(db_column='742', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_743 = models.IntegerField(db_column='743', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_744 = models.IntegerField(db_column='744', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_745 = models.IntegerField(db_column='745', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_746 = models.IntegerField(db_column='746', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_747 = models.IntegerField(db_column='747', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_748 = models.IntegerField(db_column='748', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_749 = models.IntegerField(db_column='749', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_751 = models.IntegerField(db_column='751', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_752 = models.IntegerField(db_column='752', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_753 = models.IntegerField(db_column='753', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_754 = models.IntegerField(db_column='754', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_755 = models.IntegerField(db_column='755', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_756 = models.IntegerField(db_column='756', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_757 = models.IntegerField(db_column='757', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_758 = models.IntegerField(db_column='758', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_759 = models.IntegerField(db_column='759', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_761 = models.IntegerField(db_column='761', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_762 = models.IntegerField(db_column='762', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_763 = models.IntegerField(db_column='763', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_764 = models.IntegerField(db_column='764', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_765 = models.IntegerField(db_column='765', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_766 = models.IntegerField(db_column='766', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_767 = models.IntegerField(db_column='767', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_768 = models.IntegerField(db_column='768', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_769 = models.IntegerField(db_column='769', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_771 = models.IntegerField(db_column='771', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_772 = models.IntegerField(db_column='772', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_773 = models.IntegerField(db_column='773', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_774 = models.IntegerField(db_column='774', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_775 = models.IntegerField(db_column='775', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.

    class Meta:
        managed = False
        db_table = '1_uid_restaurant'
