# Generated by Django 4.2.2 on 2023-09-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userLike', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlike',
            old_name='虱目魚',
            new_name='虱目魚焿',
        ),
    ]
