# Generated by Django 4.2.2 on 2023-09-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('rid', models.IntegerField(db_column='rID', primary_key=True, serialize=False)),
                ('rname', models.TextField(db_column='rName')),
                ('rmap_score', models.CharField(db_column='rMap_Score', max_length=10)),
                ('rphone', models.TextField(db_column='rPhone')),
                ('raddress', models.TextField(db_column='rAddress')),
                ('sun', models.CharField(blank=True, db_column='Sun', max_length=100, null=True)),
                ('mon', models.CharField(blank=True, db_column='Mon', max_length=100, null=True)),
                ('tue', models.CharField(blank=True, db_column='Tue', max_length=100, null=True)),
                ('wed', models.CharField(blank=True, db_column='Wed', max_length=100, null=True)),
                ('thur', models.CharField(blank=True, db_column='Thur', max_length=100, null=True)),
                ('fri', models.CharField(blank=True, db_column='Fri', max_length=100, null=True)),
                ('sat', models.CharField(blank=True, db_column='Sat', max_length=100, null=True)),
                ('all_label', models.CharField(max_length=100)),
                ('meal_or_not', models.IntegerField()),
            ],
            options={
                'db_table': '1_restaurant',
                'managed': False,
            },
        ),
    ]
