# Generated by Django 4.2.4 on 2023-09-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='1_restaurant',
        ),
    ]
