# Generated by Django 4.2.2 on 2023-08-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rlabel',
            fields=[
                ('rid', models.AutoField(db_column='rID', primary_key=True, serialize=False)),
                ('all_label', models.CharField(max_length=100)),
                ('label_1', models.CharField(max_length=100)),
                ('label_2', models.CharField(blank=True, max_length=100, null=True)),
                ('label_3', models.CharField(blank=True, max_length=100, null=True)),
                ('label_4', models.CharField(blank=True, max_length=100, null=True)),
                ('label_5', models.CharField(blank=True, max_length=100, null=True)),
                ('label_6', models.CharField(blank=True, max_length=100, null=True)),
                ('label_7', models.CharField(blank=True, max_length=100, null=True)),
                ('label_8', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'rlabel',
                'managed': False,
            },
        ),
    ]
