# Generated by Django 4.2.4 on 2023-09-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_info',
            table='1_user_info',
        ),
    ]
