# Generated by Django 4.2.4 on 2023-09-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_info_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_info',
            options={'managed': False},
        ),
    ]
