# Generated by Django 4.2.3 on 2023-07-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_user_users_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users_register',
        ),
    ]
